[[days]]
"date"	= "2023-06-02"
"location" = "Georgetown"
"mapUrl" = "https://goo.gl/maps/X1TwS4CkwqQyV1DUA"
"stages"= [ "jules", "coffee", "underpass", "artisan" ]
[days.schedule]
"18:00" = [ "", "", "", "" ]
"18:20" = [ "", "", "", "" ]
"18:40" = [ "", "", "", "" ]
"19:00" = [ "", "", "", "" ]
"19:20" = [ "", "", "", "" ]
"19:40" = [ "", "", "", "" ]
"20:00" = [ "", "", "", "" ]
"20:20" = [ "", "", "", "" ]
"20:40" = [ "", "", "", "" ]
"21:00" = [ "", "", "", "" ]
"21:20" = [ "", "", "", "" ]
"21:40" = [ "", "", "", "" ]
"22:00" = [ "", "", "", "" ]

[[days]]
"date"	= "2023-06-03"
"location" = "Columbia City"
"stages"= [ "valley", "hill", "gateway", "rac" ]
"mapUrl"= "https://goo.gl/maps/AWpWWjvZfAHwrNyv5"
[days.schedule]
"12:00" = [ "", "", "", "" ]
"12:20" = [ "", "", "", "" ]
"12:40" = [ "", "", "", "" ]
"13:00" = [ "", "", "", "" ]
"13:20" = [ "", "", "", "" ]
"13:40" = [ "", "", "", "" ]
"14:00" = [ "", "", "", "" ]
"14:20" = [ "", "", "", "" ]
"14:40" = [ "", "", "", "" ]
"15:00" = [ "", "", "", "" ]
"15:20" = [ "", "", "", "" ]
"15:40" = [ "", "", "", "" ]
"16:00" = [ "", "", "", "" ]
"16:20" = [ "", "", "", "" ]
"16:40" = [ "", "", "", "" ]
"17:00" = [ "", "", "", "" ]
"17:20" = [ "", "", "", "" ]
"17:40" = [ "", "", "", "" ]
"18:00" = [ "", "", "", "" ]
"18:20" = [ "", "", "", "" ]
"18:40" = [ "", "", "", "" ]
"19:00" = [ "", "", "", "" ]
"19:20" = [ "", "", "", "" ]
"19:40" = [ "", "", "", "" ]
"20:00" = [ "", "", "", "" ]

[[days]]
"date"	= "2023-06-04"
"location" = "Yesler Terrace Park"
"mapUrl" = "https://goo.gl/maps/Y2dD5U16Fqf4Fr6U8"
"stages"= [ "upper", "lower" ]
[days.schedule]
"12:00" = [ "", "" ]
"12:20" = [ "", "" ]
"12:40" = [ "", "" ]
"13:00" = [ "", "" ]
"13:20" = [ "", "" ]
"13:40" = [ "", "" ]
"14:00" = [ "", "" ]
"14:20" = [ "", "" ]
"14:40" = [ "", "" ]
"15:00" = [ "", "" ]
"15:20" = [ "", "" ]
"15:40" = [ "", "" ]
"16:00" = [ "", "" ]
"16:20" = [ "", "" ]
"16:40" = [ "", "" ]
"17:00" = [ "", "" ]
"17:20" = [ "", "" ]
"17:40" = [ "", "" ]
"18:00" = [ "", "" ]

