[jules]
name = "Jules Maes"
x = 888.0 
y = 311.0
mapUrl = "https://goo.gl/maps/JsmpL3G8BaBYjrpt6"

[coffee]
name = "Coffee Stage"
x = 950.0 
y = 835.0 
mapUrl = "https://goo.gl/maps/chBYDyvhdpfS5CHf9"

[underpass]
name = "Overpass Stage"
x = 955.0
y = 1570.0
mapUrl = "https://goo.gl/maps/A6gbnFzCF2YfHJsLA"

[artisan]
name = "Electric Stage"
x = 236.0
y = 787.0
mapUrl = "https://goo.gl/maps/NrSbrYAvS5bcco1A8"

[valley]
name = "Valley Stage"
x = 416.0
y = 1070.0
mapUrl = "https://goo.gl/maps/BLBqFWWAQqHJBhGX8"

[hill]
name = "Hill Stage"
x = 574.0
y = 500.0
mapUrl = "https://goo.gl/maps/9KWKxR7pyswJPLvx8"

[gateway]
name = "Gateway Stage"
x = 901.0
y = 1470.0
mapUrl = "https://goo.gl/maps/npUKYDL3MdtsQctg8"

[rac]
name = "Rainier Arts Stage"
x = 302.0
y = 284.0
mapUrl = "https://goo.gl/maps/DxAg4xmBYWnQR88d9"

[upper]
name = "Spray Stage"
x = 1175.0
y = 735.0
mapUrl = "https://goo.gl/maps/SuYFTkq48jrPhs5Y8"

[lower]
name = "Lawn Stage"
x = 170.0
y = 1000.0
mapUrl = "https://goo.gl/maps/KPwtYko3d9EhzeXT6"
