[friday]
"stages"= [ "Flying Fernando", "Golden Garth", "Sara Tops", "Artisan Extinction" ]
[friday.schedule]
"18:00" = [ "onelove", "funkrust", "filthy", "allstars" ]
"18:20" = [ "onelove", "funkrust", "filthy", "burnout" ]

[saturday]
"stages"= [ "Flying Fernando", "Golden Garth", "Sara Tops", "Artisan Extinction" ]
[saturday.schedule]
"18:00" = [ "onelove", "funkrust", "filthy", "allstars" ]
"18:20" = [ "onelove", "funkrust", "filthy", "burnout" ]

[sunday]

